version: "3"

services:
  api:
    build: 
      context: api/
      args:
        - DB_NAME=${DB_NAME}
    container_name: domofomka-api
    expose:
      - 80
    environment:
      - DADATA_TOKEN=${DADATA_TOKEN}
  vkbot:
    build: vkbot/
    container_name: domofomka-vkbot
    # restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOMOFOMKA_API_HOST=api
      - DOMOFOMKA_API_PORT=80
      - VK_GROUP_TOKEN=${VK_GROUP_TOKEN}
      - VK_GROUP_ID=${VK_GROUP_ID}
  redis:
    image: redis
    container_name: domofomka-redis
    expose:
      - 6379
    


